# Generated by Django 4.2.24 on 2025-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
