# Generated by Django 4.2.24 on 2025-09-30 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_link_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Handle must be 5–15 chars, lowercase letters, numbers, or underscore.', regex='^[a-z0-9_]{5,15}$')]),
        ),
    ]
