# Generated by Django 4.2.24 on 2025-10-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_handle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['position', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='link',
            name='uniq_link_sort_per_profile',
        ),
        migrations.RemoveIndex(
            model_name='link',
            name='profiles_li_profile_a8a27f_idx',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='sort_order',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='link',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['profile', 'position'], name='profiles_li_profile_137c59_idx'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('profile', 'position'), name='uniq_link_position_per_profile'),
        ),
    ]
